// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msdwgsotkxhuppjrffqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zZHdnc290a3hodXBwanJmZnF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNjM2NTYsImV4cCI6MjA2OTgzOTY1Nn0.jD13wFzn2dbC92i0oZ2MaWCvFpU-0hh4T2E3kU99FGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});